# Generated by Django 4.0.2 on 2022-02-02 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, max_length=512, null=True, unique=True)),
                ('person_pinfl', models.CharField(blank=True, max_length=512, null=True)),
                ('person_passportSeries', models.CharField(blank=True, max_length=512, null=True)),
                ('person_passportNumber', models.CharField(blank=True, max_length=512, null=True)),
                ('person_firstname', models.CharField(blank=True, max_length=512, null=True)),
                ('person_lastname', models.CharField(blank=True, max_length=512, null=True)),
                ('person_middlename', models.CharField(blank=True, max_length=512, null=True)),
                ('person_phoneNumber', models.CharField(blank=True, max_length=512, null=True)),
                ('person_gender', models.CharField(blank=True, max_length=512, null=True)),
                ('person_birthDate', models.CharField(blank=True, max_length=512, null=True)),
                ('address', models.CharField(blank=True, max_length=512, null=True)),
                ('email', models.CharField(blank=True, default='default@agros.uz', max_length=512, null=True)),
                ('payment_type', models.CharField(blank=True, max_length=512, null=True)),
                ('person_data', models.JSONField(blank=True, null=True)),
                ('policy_title', models.CharField(blank=True, default='Baxtsiz hodisa', max_length=1024, null=True)),
                ('policy_start_date', models.DateField(blank=True, null=True)),
                ('policy_end_date', models.DateField(blank=True, null=True)),
                ('policy_seria', models.CharField(blank=True, default='UZIN-BH', max_length=100, null=True)),
                ('policy_number', models.IntegerField(blank=True, null=True)),
                ('policy_insurancePremium', models.IntegerField(blank=True, default=10000, null=True)),
                ('policy_sumInsured', models.IntegerField(blank=True, default=10000000, null=True)),
                ('policy_pdf', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
    ]
