# Generated by Django 4.0.2 on 2022-02-02 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='slug',
            field=models.SlugField(blank=True, max_length=512, null=True),
        ),
    ]
