# Generated by Django 4.0.2 on 2022-02-02 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0002_alter_contract_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='policy_insurancePremium_word',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='Страховая премия с прописью'),
        ),
        migrations.AddField(
            model_name='contract',
            name='policy_sumInsured_word',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='Страховая ответственность с прописью'),
        ),
    ]
