# Generated by Django 4.0.2 on 2022-02-03 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0003_contract_policy_insurancepremium_word_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='qr_code',
            field=models.URLField(blank=True, null=True, verbose_name='QRCODE url'),
        ),
    ]
